# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_cpp <- function(X, beta, P, XP, fit_interactions) {
    .Call('_survivalfm_predict_cpp', PACKAGE = 'survivalfm', X, beta, P, XP, fit_interactions)
}

negative_log_likelihood <- function(linear_predictors, status, time) {
    .Call('_survivalfm_negative_log_likelihood', PACKAGE = 'survivalfm', linear_predictors, status, time)
}

regularized_negative_log_likelihood <- function(status, time, lp, cumsum_exp_lp, P, beta, lambda1, lambda2, fit_interactions) {
    .Call('_survivalfm_regularized_negative_log_likelihood', PACKAGE = 'survivalfm', status, time, lp, cumsum_exp_lp, P, beta, lambda1, lambda2, fit_interactions)
}

shared_computations <- function(X, beta, P, fit_interactions) {
    .Call('_survivalfm_shared_computations', PACKAGE = 'survivalfm', X, beta, P, fit_interactions)
}

compute_gradients <- function(X, status, time, P, beta, XP, exp_lp, cumsum_exp_lp, lambda1, lambda2, fit_interactions) {
    .Call('_survivalfm_compute_gradients', PACKAGE = 'survivalfm', X, status, time, P, beta, XP, exp_lp, cumsum_exp_lp, lambda1, lambda2, fit_interactions)
}

